/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Test: typeof import('./resources/js/vue/components/Test.vue')['default']
    TestAgain: typeof import('./resources/js/vue/components/TestAgain.vue')['default']
  }
}
